nominatim:
  ports:
    - '8181:8080'
    - '5432:5432'
  environment:
    - 'NOMINATIM_PBF_URL=https://download.geofabrik.de/asia/malaysia-singapore-brunei-latest.osm.pbf'
  image: 'nominatim:latest'
  restart: unless-stopped


photon:
  ports:
    - '2322:2322'
  links:
    - 'nominatim:nominatim'
  image: 'photon:latest'
  restart: unless-stopped


graphhopper:
  ports:
    - '8989:8989'
  image: 'graphhopper:latest'
  volumes:
    - '<path_geolocation-services_directory>/data:/data'
  restart: unless-stopped